# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Torpido.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color :  rgb(0, 0, 0);")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 120, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Yanone Kaffeesatz")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("color: rgb(238, 238, 236);")
        self.label.setObjectName("label")
        self.videofileinfo = QtWidgets.QTextBrowser(self.centralwidget)
        self.videofileinfo.setGeometry(QtCore.QRect(360, 160, 311, 91))
        self.videofileinfo.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.videofileinfo.setStatusTip("")
        self.videofileinfo.setAutoFillBackground(False)
        self.videofileinfo.setStyleSheet("background-color: rgb(85, 87, 83);")
        self.videofileinfo.setObjectName("videofileinfo")
        self.introextro = QtWidgets.QLabel(self.centralwidget)
        self.introextro.setGeometry(QtCore.QRect(80, 270, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Yanone Kaffeesatz")
        font.setPointSize(15)
        self.introextro.setFont(font)
        self.introextro.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.introextro.setAutoFillBackground(False)
        self.introextro.setStyleSheet("color: rgb(238, 238, 236);")
        self.introextro.setObjectName("introextro")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(340, 330, 121, 23))
        font = QtGui.QFont()
        font.setFamily("Yanone Kaffeesatz")
        font.setPointSize(14)
        self.checkBox.setFont(font)
        self.checkBox.setAutoFillBackground(False)
        self.checkBox.setStyleSheet("color: rgb(238, 238, 236);\n"
"gridline-color: rgb(238, 238, 236);\n"
"")
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(540, 330, 121, 23))
        font = QtGui.QFont()
        font.setFamily("Yanone Kaffeesatz")
        font.setPointSize(14)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setAutoFillBackground(False)
        self.checkBox_2.setStyleSheet("color: rgb(238, 238, 236);")
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(340, 380, 121, 23))
        font = QtGui.QFont()
        font.setFamily("Yanone Kaffeesatz")
        font.setPointSize(14)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setAutoFillBackground(False)
        self.checkBox_3.setStyleSheet("color: rgb(238, 238, 236);")
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_4.setGeometry(QtCore.QRect(540, 380, 121, 23))
        font = QtGui.QFont()
        font.setFamily("Yanone Kaffeesatz")
        font.setPointSize(14)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setAutoFillBackground(False)
        self.checkBox_4.setStyleSheet("color: rgb(238, 238, 236);")
        self.checkBox_4.setObjectName("checkBox_4")
        self.dispvout = QtWidgets.QCheckBox(self.centralwidget)
        self.dispvout.setGeometry(QtCore.QRect(110, 440, 171, 23))
        font = QtGui.QFont()
        font.setFamily("Yanone Kaffeesatz")
        font.setPointSize(14)
        self.dispvout.setFont(font)
        self.dispvout.setAutoFillBackground(False)
        self.dispvout.setStyleSheet("color: rgb(238, 238, 236);")
        self.dispvout.setObjectName("dispvout")
        self.dispvout_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.dispvout_2.setGeometry(QtCore.QRect(110, 490, 171, 23))
        font = QtGui.QFont()
        font.setFamily("Yanone Kaffeesatz")
        font.setPointSize(14)
        self.dispvout_2.setFont(font)
        self.dispvout_2.setAutoFillBackground(False)
        self.dispvout_2.setStyleSheet("color: rgb(238, 238, 236);")
        self.dispvout_2.setObjectName("dispvout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(320, 40, 181, 71))
        font = QtGui.QFont()
        font.setFamily("Purisa")
        font.setPointSize(25)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("color: rgb(238, 238, 236);")
        self.label_2.setObjectName("label_2")
        self.startbutton = QtWidgets.QPushButton(self.centralwidget)
        self.startbutton.setGeometry(QtCore.QRect(350, 460, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Yanone Kaffeesatz")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.startbutton.setFont(font)
        self.startbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.startbutton.setAutoFillBackground(False)
        self.startbutton.setStyleSheet("background-color :  rgb(164, 0, 0);\n"
"color: rgb(238, 238, 236);")
        self.startbutton.setProperty("color", QtGui.QColor(164, 0, 0))
        self.startbutton.setProperty("Background color", QtGui.QColor(204, 0, 0))
        self.startbutton.setObjectName("startbutton")
        self.cancelbutton = QtWidgets.QPushButton(self.centralwidget)
        self.cancelbutton.setGeometry(QtCore.QRect(530, 460, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Yanone Kaffeesatz")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.cancelbutton.setFont(font)
        self.cancelbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancelbutton.setAutoFillBackground(False)
        self.cancelbutton.setStyleSheet("background-color :  rgb(78, 154, 6);\n"
"color: rgb(238, 238, 236);")
        self.cancelbutton.setObjectName("cancelbutton")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(80, 540, 621, 23))
        font = QtGui.QFont()
        font.setFamily("Yanone Kaffeesatz")
        font.setPointSize(14)
        self.progressBar.setFont(font)
        self.progressBar.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        self.progressBar.setStyleSheet("color: rgb(238, 238, 236);\n"
"background-color: rgb(238, 238, 236);")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Select Video file to process"))
        self.videofileinfo.setToolTip(_translate("MainWindow", "Select file to Display info"))
        self.introextro.setText(_translate("MainWindow", "Select intro and extro video files"))
        self.checkBox.setText(_translate("MainWindow", "    option #1"))
        self.checkBox_2.setText(_translate("MainWindow", "    option #1"))
        self.checkBox_3.setText(_translate("MainWindow", "    option #3"))
        self.checkBox_4.setText(_translate("MainWindow", "    option #4"))
        self.dispvout.setText(_translate("MainWindow", "     Display Video Output"))
        self.dispvout_2.setText(_translate("MainWindow", "     Display Audio Output"))
        self.label_2.setText(_translate("MainWindow", "TorPido"))
        self.startbutton.setText(_translate("MainWindow", "Start"))
        self.cancelbutton.setText(_translate("MainWindow", "Cancel"))

